### ISSUE TITLE
 super() takes at least 1 argument

### ISSUE THREAD

**Issue by kuzlovsky** [nanopony/keras-convautoencoder#1]
Hello nanopony,

When running python conv_autoencoder.py I get:

Using Theano backend.
Traceback (most recent call last):
  File "conv_autoencoder.py", line 50, in <module>
    model = build_model()
  File "conv_autoencoder.py", line 37, in build_model
    model.add(DependentDense(nb_filters \* 14 \* 14, d))
  File "/mnt/persistent/tutorial/keras-convautoencoder/autoencoder_layers.py", line 279, in **init**
    super().**init**(output_dim, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

When you do a clean clone of your project does it work for you? If yes then something is wrong on my system, if no then I assume it's a recent change. Could you please confirm?

Thanks a lot

Regards,
Joe

**Comment by brijmohan** [comment]
Hi nanopony,

I am facing the same issue as mentioned by Joe. Please suggest if there are any changes to be made.

Thanks.

**Comment by nanopony** [comment]
@kuzlovsky @brijmohan What version of python are you using? If it is Python2.x, you might be required to fix ancestor call, since shorthand super() was introduced in Python3

**Comment by nanopony** [comment]
Closing by now. For further reference, I use Python3.4
