### ISSUE TITLE
Weight-tieing?

### ISSUE THREAD

**Issue by ArturoDeza** [nanopony/keras-convautoencoder#11]
I can't seem to find where in the code is the weight tieing happening, unless I missed something pretty obvious.

**Comment by nanopony** [comment]
In https://github.com/nanopony/keras-convautoencoder/blob/c8172766f968c8afc81382b5e24fd4b57d8ebe71/autoencoder_layers.py#L197
we take weights from binded conv layer and reuse them in the corresponding deconv layer
