### ISSUE TITLE
FCC-convolutinal AE

### ISSUE THREAD

**Issue by ehfo0** [nanopony/keras-convautoencoder#9]
Fcc.py
when I try to run the code I get this error:
`Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
would u help me fix it??

**Comment by nanopony** [comment]
Looks like the issue is related to yours Intel Mkl installation. It is failing to find its libraries. This code doesn't require Intel Mkl.

**Comment by ehfo0** [comment]
@nanopony thanks for the quick reply I fixed the mkl.
